Implementation of Rest-Support
faktorzehn/jira-gerrit-plugin pull request #1
Opened 2022-06-15 05:25 UTC by ManuelMuehlberger

Both IssueReviewsCacheLoader and AdminServlet can now establish a Rest-connection to Gerrit with the help of a modified gerrit-events dependency.

2022-06-20 07:59 UTC, f10mlupfer requested changes
nicht von der Anzahl der Kommentare erschlagen lassen. Aber noch ein paar Dinge...

2022-06-20 07:59 UTC, f10mlupfer commented on pom.xml
> +            <version>2.20.1</version>
für das lokale Testen muss man hier -SNAPSHOT angeben, da die 2.20.1 noch nicht released ist. Wahrscheinlich ist das erstmal besser so, bis wir das final released haben

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
hat nichts mit der Zeile zu tun, aber beim bauen bekomme ich beim javadoch einen Fehler, dass die <tt> Tags nicht supported sind => <tt>gerrit review [ChangeId] ...</tt> (Zeile 40)
?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/GerritCommand.java
> +    //Rest support not needed, unused method
wenn die Methode nicht verwendet wird, warum wird sie dann nicht entfernt (und ggf. weitere, die dadurch evtl. unnötig werden)?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +                List<JSONObject> s = query.queryJava("limit:1", false, false, false);
mit "s" wird nichts gemacht

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +                    //() -> ""; lambdas are tripping up CheckStyle
kann das raus oder was ist damit?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +            //https://toolsqa.com/rest-assured/rest-api-test-using-rest-assured/
hat sich das TODO erledigt?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +    protected static Logger log = LoggerFactory.getLogger(AdminServlet.class);
muss der protected sein? die Klasse wird doch nicht abgeleitet

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +//class is described in detail here:    https://developer.atlassian.com/server/framework/atlassian-sdk/creating-an-admin-configuration-form/
hier würde einen richtigen JavaDoc Kommentar bevorzugen, bspw.
/**
  \* @see https://developer.atlassian.com/server/framework/atlassian-sdk/creating-an-admin-configuration-form/
 */

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/GerritConfigurationImpl.java
> +    }
Formatierung

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/GerritConfigurationImpl.java
> +
Unnötige Leerzeilen

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoader.java
> +                // return Collections.emptyList();
kann das raus?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoader.java
> +                    //() -> ""; lambdas are tripping up CheckStyle
und das?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoader.java
> +                // return Collections.emptyList();
?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritApproval.java
> +import com.sonymobile.tools.gerrit.gerritevents.dto.attr.Approval;
wird nirgends verwendet

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritApproval.java
> +        //return by;
?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritChange.java
> +             */
ist das etwas, was wir für die Zukunft im Auge behalten sollten oder kann das raus?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritChange.java
> +    public String getStatusString() {
wird die Methode überhaupt verwendet. Wenn nicht raus, ansonsten, was spricht gegen getStatus()?

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/tabpanel/GerritReviewsTabPanel.java
> +//import com.atlassian.sal.api.user.UserManager;
kann raus

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/webpanel/GerritReviewsIssueAgilePanel.java
> +{
Formatierung sollte einheitlich sein, ggf. über alles mal drüber und neu formatieren

2022-06-20 07:59 UTC, f10mlupfer commented on src/main/resources/gerrit-events/pom.xml
> +        </dependency>-->
können dieses auskommentierten Dependencies raus?

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +    }
kann man das in ein @Before mit dem oberen packen? Hier macht es ggf. nichts aus, aber in manchen Fällen ist es sinnvoll zu wissen, dass erst das eine, dann das andere ausgeführt wird. Bei zwei Methoden weiß man das nie so genau, welche als erste ausgeführt wird...

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +        //.usingFilesUnderDirectory("src/test/"));
das braucht es dann wahrscheinlich auch nicht?

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +        System.out.println(map.toString());
die System.out Befehle würde ich rausnehmen (zumindest auskommentieren, in den Tests als auskommentiert fände ich auch ok.)

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +        System.out.println("Testresult: " + map.get("testResult"));
hier würde ich sagen, System.out ist ok, da man das wahrscheinlich nur lokal einkommentiert und den Test kurz gegen einen richtigen Server laufen lässt.

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoaderTest.java
> +        //.usingFilesUnderDirectory("src/test/"));
kann raus

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +    {
könntest du mal schauen, ob du den Code durchgängig gleich formatiert bekommst? ggf. auch in Richtung "wie er im Original" formatiert ist, ansonsten würde es noch mehr Änderungen geben.

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoaderTest.java
> +                                "[{\"id\":\"test0%2Ftest0.test~master~Id145cfc4s2d6fek18c3539gbi8me1d3e37501568\",\"project\":\"test0/test0.test\",\"branch\":\"master\",\"attention_set\":{\"309\":{\"
kann man das nicht aus der Datei laden?

2022-06-20 07:59 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/data/dto/GerritApprovalTest.java
>      private static void assertFull(GerritApproval obj) {
muss die static sein?

2022-06-23 08:43 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/data/GerritCommand.java
> +    //Rest support not needed, unused method
Keine Ahnung, warum die als depreciated markiert wurde. Die Methode wird benutzt, es gibt außerdem auch keine andere Methode, welche diese ablösen würde. Markierung entfernt

2022-06-23 08:51 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +            //https://toolsqa.com/rest-assured/rest-api-test-using-rest-assured/
Habe ich mal umgelabelt zu "future idea". Besseres Url checking wäre ein Nice-to-have, das bisherige, eher rudimentäre, sollte aber auch OK sein.

2022-06-23 09:12 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritApproval.java
> +        //return by;
GerritApproval erbt aus einer Klasse von gerrit-events. Dort wurde der Rückgabewert bei einer der neueren Versionen von String auf eine "Account"klasse geändert, was die originale Methode zerschossen hat... Da wir aber manchmal nur den Namen des Approvers brauchen, habe ich einfach die Signatur geändert. (jetzt auf getByName() damit es klarer ist)

2022-06-23 09:14 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritChange.java
> +             */
Code von dem Fork, der eh nicht funktioniert hat und ich durch meinen URL-Parser ersetzt habe. Kann raus.

2022-06-23 09:16 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritChange.java
> +    public String getStatusString() {
wie oben, veränderte Superklasse. Kann aber raus.

2022-06-23 09:26 UTC, ManuelMuehlberger commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +    }
habe jetzt bei einem die Annotation entfernt, wird am Ende der anderen aufgerufen.

2022-06-23 09:28 UTC, ManuelMuehlberger commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +        //.usingFilesUnderDirectory("src/test/"));
Meinst du damit den Kommentar?

2022-06-23 09:51 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/webpanel/GerritReviewsIssueAgilePanel.java
> +{
Hab alles mal durch den Formatter laufen lassen

2022-06-23 10:21 UTC, ManuelMuehlberger commented on src/test/java/com/meetme/plugins/jira/gerrit/data/IssueReviewsCacheLoaderTest.java
> +                                "[{\"id\":\"test0%2Ftest0.test~master~Id145cfc4s2d6fek18c3539gbi8me1d3e37501568\",\"project\":\"test0/test0.test\",\"branch\":\"master\",\"attention_set\":{\"309\":{\"
Directory der Dateien musste geändert werden, geht jetzt.

2022-06-23 10:34 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
Kann ich jetzt leider nicht reproduzieren... Kannst du mir da noch etwas mehr Detail geben?

2022-06-27 05:29 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
ich habe einfach mvn clean install auf dem Projekt aufgerufen. Hat es evtl. etwas mit der maven Version zu tun?

2022-06-27 05:33 UTC, f10mlupfer requested changes
Hast du die Änderungen schon veröffentlicht?

2022-06-27 05:33 UTC, f10mlupfer commented on src/test/java/com/meetme/plugins/jira/gerrit/adminui/AdminServletTest.java
> +        //.usingFilesUnderDirectory("src/test/"));
das hier //.usingFilesUnderDirectory("src/test/"));

2022-06-27 05:33 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
ich habe einfach mvn clean install auf dem Projekt aufgerufen. Hat es evtl. etwas mit der maven Version zu tun?

2022-06-27 05:33 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
> +            //https://toolsqa.com/rest-assured/rest-api-test-using-rest-assured/
ok. Ansonsten könntest du es so drin lassen und ggf. im Wiki dazu noch einen zusätzlichen Absatz bzgl. Verbesserungen/Improvements/TODOs

2022-06-29 08:07 UTC, ManuelMuehlberger commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
Ich habe jetzt mal ne Weile mit verschiedenen Maven und Atlassian-maven Versionen getestet, ich komme aber nur zu einem von zwei Ergebnissen: 1. mit Atlassian-mvn funktioniert alles (Spotbugs hat sich noch beschwert, dass die mvn version nichtmehr unterstützt wird, ich kann mir aber nicht vorstellen, dass das Einfluss auf javadoc hat -> version etwas downgegradet) oder 2. mit normalen Maven kann er die besonderen atlassian-Dependencies nicht finden

2022-07-08 05:22 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/workflow/function/ApprovalFunction.java
> +import com.sonymobile.tools.gerrit.gerritevents.GerritQueryException;
also wenn es so durchläuft ist es ja erstmal für mich ok!

2022-07-08 05:56 UTC, f10mlupfer requested changes
könntest du nochmal über den ganzen Code drüber schauen (ok, zugegeben, der war ja vorher schon nicht schön), und mal prüfen, was es noch an Code gibt, welcher nicht verwerndet wird oder unnötige Annotations bspw. (@SuppressWarnings("unchecked") in GerritReviewsIssueAgilePanel) gibt und aufräumen?
Ich finde, in diesem Zug könnten wir da gerade noch ein wenig aufräumen

2022-07-08 05:56 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/adminui/AdminServlet.java
>      private static final String ACTION_SAVE = "save";
hab gerade noch gesehen, dass das ACTION_SAVE nicht verwendet wird

2022-07-08 05:56 UTC, f10mlupfer commented on pom.xml
> +            </exclusions>
noch mal kurz zu den ganzen exclusions, im speziellen org.slf4j, da das ja eigentlich immer exluded wird. Ist das wirklich notwendig? Haben wir das gemacht, weil wir ansonsten viele unterschiedlichen Versionen davon haben?

2022-07-08 05:56 UTC, f10mlupfer commented on src/main/java/com/meetme/plugins/jira/gerrit/data/dto/GerritChange.java
> -
status wird auch nicht mehr verwendet?

2022-07-13 11:41 UTC, merged